name: Build and Upload Artifacts

on:
  push:
    branches:
      - artifact
  pull_request:
   #branches:
   #  - main
   #  - master

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_linux'

  windows-build:
    runs-on: windows-2019
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_windows'

  osx-build:
    runs-on: macos-12
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_osx'
